services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: mcp-series-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MCP Server
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-series-server
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      MCP_PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - /app/node_modules
    networks:
      - mcp-network
    command: npm start

networks:
  mcp-network:
    name: mcp-series-network

volumes:
  postgres_data:
    name: mcp-series-data
